name: Create Release Archive

on:
  push:
    tags:
      - "v*.*.*" # Trigger on version tags
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create archive
        run: |
          git archive --format=zip --output=chrome109.zip HEAD chrome109/

      - name: Create Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: chrome109.zip